### ISSUE TITLE
Error in language_row.py module

### ISSUE THREAD

**Issue by soumyaDghosh** [TenderOwl/Frog#112]
Hello, I have been snapping this app, but at the end, I'm getting this error.

```
Traceback (most recent call last):
  File "/snap/frog/x1/usr/bin/frog", line 59, in <module>
    from frog import main
  File "/snap/frog/x1/usr/lib/python3/dist-packages/frog/main.py", line 46, in <module>
    from .window import FrogWindow
  File "/snap/frog/x1/usr/lib/python3/dist-packages/frog/window.py", line 38, in <module>
    from .language_dialog import LanguageItem
  File "/snap/frog/x1/usr/lib/python3/dist-packages/frog/language_dialog.py", line 33, in <module>
    from .language_row import LanguageRow
  File "/snap/frog/x1/usr/lib/python3/dist-packages/frog/language_row.py", line 8, in <module>
    class LanguageRow(Gtk.Overlay):
  File "/snap/frog/x1/usr/lib/python3/dist-packages/frog/language_row.py", line 13, in LanguageRow
    progress_bar: Gtk.ProgressBar = Gtk.Template.Child()
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/module.py", line 173, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/module.py", line 95, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/module.py", line 213, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/snap/frog/x1/gnome-platform/usr/lib/python3/dist-packages/gi/types.py", line 247, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface

```

Can you please help me fix this.

**Comment by amka** [comment]
@soumyaDghosh sry for the late response. Not sure what happened inside the snap. Maybe the GTK version is a bit odd or there are not enough .gir files. Could you point me to the `snap` file to check it locally?

**Comment by soumyaDghosh** [comment]
Sorry, forgot to inform you. The snap is working and in the store now

**Comment by soumyaDghosh** [comment]
Currently there are 85 active users. But, I guess it can increase if this is added in your repo

Markdown

```
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/frog)
```
HTML

```
<a href="https://snapcraft.io/frog">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>
```
