### ISSUE TITLE
TypeError: init() missing 1 required positional argument: 'argv'

### ISSUE THREAD

**Issue by yochananmarqos** [TenderOwl/Frog#128]
1.4.0 fails to start after building from source:

```
❯ frog
Traceback (most recent call last):
  File "/usr/bin/frog", line 59, in <module>
    from frog import main
  File "/usr/lib/python3.11/site-packages/frog/main.py", line 40, in <module>
    from frog.window import FrogWindow
  File "/usr/lib/python3.11/site-packages/frog/window.py", line 41, in <module>
    from frog.widgets.extracted_page import ExtractedPage
  File "/usr/lib/python3.11/site-packages/frog/widgets/extracted_page.py", line 32, in <module>
    from frog.services.tts import ttsservice, TTSService
  File "/usr/lib/python3.11/site-packages/frog/services/tts.py", line 71, in <module>
    ttsservice = TTSService()
                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/frog/services/tts.py", line 23, in __init__
    Gst.init()
TypeError: init() missing 1 required positional argument: 'argv'
```

**Comment by amka** [comment]
@yochananmarqos Not sure how to reproduce it. Could you provide me with more details?

**Comment by yochananmarqos** [comment]
I'm the maintainer of the [`frog-ocr` ](https://aur.archlinux.org/packages/frog-ocr)AUR package. I've built 1.4.0 with this updated PKGBUILD:

<details>
<summary>PKGBUILD</summary>

```
# Maintainer: Mark Wagie <mark dot wagie at proton dot me>
pkgname=frog-ocr
pkgver=1.4.0
pkgrel=1
pkgdesc="Intuitive text extraction tool (OCR) for GNOME."
arch=('any')
url="https://tenderowl.com/work/frog"
license=('MIT')
depends=('leptonica' 'libadwaita' 'libnotify' 'libportal' 'python-gobject'
         'python-gtts' 'python-pydbus' 'python-pytesseract' 'pyzbar')
makedepends=('blueprint-compiler' 'meson')
checkdepends=('appstream-glib')
install="$pkgname.install"
source=("Frog-$pkgver.tar.gz::https://github.com/TenderOwl/Frog/archive/refs/tags/$pkgver.tar.gz")
sha256sums=('8d5616dd6f4ac24cc8c354bab39363318a324c6679d68b4a9ec0fb2ecf154894')

prepare() {
  cd "Frog-$pkgver"

  # Fix path to appdata
  sed -i 's|/app/share/|/usr/share/|g' frog/language_manager.py
}

build() {
  arch-meson "Frog-$pkgver" build
  meson compile -C build
}

check() {
  meson test -C build --print-errorlogs || :
}

package() {
  meson install -C build --destdir "$pkgdir"

  cd "Frog-$pkgver"
  install -Dm644 COPYING -t "$pkgdir/usr/share/licenses/$pkgname/"
}
```

</details>

**Comment by amka** [comment]
Hmm, no idea why you get this error. Due to GST docs, it could take `None`. 
https://lazka.github.io/pgi-docs/#Gst-1.0/functions.html#Gst.init

You could try to add an empty string:
```python
Gst.init("")
```

I'll check it for the Flatpak version yet it will wait for a new release.

**Comment by yochananmarqos** [comment]
Add it where? I'm a package maintainer, not a programmer.
