### ISSUE TITLE
Unable to find zbar shared library

### ISSUE THREAD

**Issue by jk-1** [TenderOwl/Frog#204]
I tried to install and run frog but got following error. 

```
snap info frog
name:      frog
summary:   Extract text from images
publisher: সৌম্যদীপ ঘোষ(Soumyadeep Ghosh) (soumyadghosh)
store-url: https://snapcraft.io/frog
license:   MIT
description: |
  Extract text from images, websites, videos, and QR codes by taking a picture of the source.
snap-id: tGKXJEtiJPjrw0iZQPaWsJiALdmdG1xF
channels:
  latest/stable:    1.5.1 2024-05-11 (27) 24MB -
  latest/candidate: 1.5.1 2024-05-11 (27) 24MB -
  latest/beta:      1.5.1 2024-05-11 (27) 24MB -
  latest/edge:      1.5.1 2024-05-11 (27) 24MB -

```
```
jk@h10:~$ sudo snap install frog
frog 1.5.1 from সৌম্যদীপ ঘোষ(Soumyadeep Ghosh) (soumyadghosh) installed

```
```
jk@h10:~$ which frog
/snap/bin/frog

```
```
jk@h10:~$ frog --version
Traceback (most recent call last):
  File "/snap/frog/27/usr/bin/frog", line 59, in <module>
    from frog import main
  File "/snap/frog/27/usr/lib/python3/dist-packages/frog/main.py", line 40, in <module>
    from frog.services.screenshot_service import ScreenshotService
  File "/snap/frog/27/usr/lib/python3/dist-packages/frog/services/screenshot_service.py", line 42, in <module>
    from pyzbar.pyzbar import decode
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library

jk@h10:~$ frog 
Traceback (most recent call last):
  File "/snap/frog/27/usr/bin/frog", line 59, in <module>
    from frog import main
  File "/snap/frog/27/usr/lib/python3/dist-packages/frog/main.py", line 40, in <module>
    from frog.services.screenshot_service import ScreenshotService
  File "/snap/frog/27/usr/lib/python3/dist-packages/frog/services/screenshot_service.py", line 42, in <module>
    from pyzbar.pyzbar import decode
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/snap/frog/27/usr/lib/python3/dist-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library

```

My OS is `Ubuntu 22.04.4 LTS`

```
python3 --version
Python 3.10.12
```
How to fix this issue?

**Comment by Acerlorion** [comment]
Try to install `zbar-tools` with `sudo apt install zbar-tools`

**Comment by marventu94** [comment]
Thanks @Acerlorion  for the code. It worked perfectly.

I would like to ask if there is a way to install this dependency directly inside Snap to avoid this error. I installed Frog directly from Snap but it didn't work until I installed the lib via apt. I understand that doing this kind of extra step goes against the idea of ​​Snap, which is meant to simplify package management.

Can this be done?
